import {CONFIG} from "./config.js";
import {normalize,debounce,escapeHtml} from "./utils.js";
const FALLBACK=[
 ["CDG","LFPG","Paris Charles de Gaulle","Paris","FR",49.0097,2.5479],["ORY","LFPO","Paris Orly","Paris","FR",48.7262,2.3652],["JFK","KJFK","John F Kennedy International","New York","US",40.6413,-73.7781],["LAX","KLAX","Los Angeles International","Los Angeles","US",33.9416,-118.4085],["LHR","EGLL","London Heathrow","London","GB",51.47,-0.4543],["DXB","OMDB","Dubai International","Dubai","AE",25.2532,55.3657],["SIN","WSSS","Singapore Changi","Singapore","SG",1.3644,103.9915],["HND","RJTT","Tokyo Haneda","Tokyo","JP",35.5494,139.7798],["FRA","EDDF","Frankfurt Main","Frankfurt","DE",50.0379,8.5622],["AMS","EHAM","Amsterdam Schiphol","Amsterdam","NL",52.3105,4.7683],["ATL","KATL","Hartsfield Jackson Atlanta","Atlanta","US",33.6407,-84.4277],["SYD","YSSY","Sydney Kingsford Smith","Sydney","AU",-33.9399,151.1753]
].map(([iata,icao,name,city,country,lat,lon])=>({iata,icao,name,city,country,lat,lon,type:"large_airport",scheduled:true}));
function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function shape(csv){const rows=parseCsv(csv),header=rows.shift(),idx=Object.fromEntries(header.map((h,i)=>[h,i]));return rows.map(r=>({iata:(r[idx.iata_code]||"").toUpperCase(),icao:(r[idx.icao_code]||r[idx.gps_code]||r[idx.ident]||"").toUpperCase(),name:r[idx.name]||"Unknown airport",city:r[idx.municipality]||"",country:r[idx.iso_country]||"",lat:Number(r[idx.latitude_deg]),lon:Number(r[idx.longitude_deg]),type:r[idx.type]||"",scheduled:r[idx.scheduled_service]==="yes"})).filter(a=>Number.isFinite(a.lat)&&Number.isFinite(a.lon)&&(a.iata||a.icao)&&!["closed","heliport","seaplane_base","balloonport"].includes(a.type))}
function enrich(list){return list.map((a,id)=>({...a,id,search:normalize(`${a.iata} ${a.icao} ${a.name} ${a.city} ${a.country}`)}))}
export async function loadAirports(onProgress=()=>{}){try{const cached=localStorage.getItem(CONFIG.CACHE_VERSION);if(cached){const parsed=JSON.parse(cached);if(Array.isArray(parsed)&&parsed.length>1000){onProgress(`${parsed.length.toLocaleString()} airports loaded from cache`);return enrich(parsed)}}onProgress("Downloading worldwide airport database…");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),CONFIG.REQUEST_TIMEOUT_MS);const res=await fetch(CONFIG.AIRPORTS_URL,{signal:controller.signal});clearTimeout(timer);if(!res.ok)throw new Error(`Airport data HTTP ${res.status}`);const list=shape(await res.text());try{localStorage.setItem(CONFIG.CACHE_VERSION,JSON.stringify(list))}catch{}onProgress(`${list.length.toLocaleString()} airports ready`);return enrich(list)}catch(e){console.warn("Full airport database unavailable; fallback enabled",e);onProgress("Offline fallback airport list enabled");return enrich(FALLBACK)}}
export function searchAirports(index,query,limit=CONFIG.SEARCH_LIMIT){const q=normalize(query);if(!q)return index.filter(a=>a.scheduled&&a.iata).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,limit);const tokens=q.split(" ");return index.filter(a=>tokens.every(t=>a.search.includes(t))).map(a=>{let score=0;if(a.iata.toLowerCase()===q)score-=100;if(a.icao.toLowerCase()===q)score-=90;if(a.iata.toLowerCase().startsWith(q))score-=50;if(a.icao.toLowerCase().startsWith(q))score-=45;if(a.scheduled)score-=12;if(a.type==="large_airport")score-=8;return{a,score}}).sort((x,y)=>x.score-y.score||x.a.name.localeCompare(y.a.name)).slice(0,limit).map(x=>x.a)}
export function createAirportPicker({input,results,choice,index,onSelect}){let selected=null,active=-1,current=[];const close=()=>{results.hidden=true;active=-1};const choose=a=>{selected=a;input.value=a.iata||a.icao;choice.textContent=`${a.name} • ${a.city||a.country} • ${a.icao}`;close();onSelect(a)};const render=()=>{current=searchAirports(index,input.value);results.innerHTML=current.length?current.map((a,i)=>`<button type="button" role="option" class="airport-result" data-i="${i}"><span class="airport-code">${escapeHtml(a.iata||a.icao)}</span>${escapeHtml(a.name)}<span class="airport-meta">${escapeHtml([a.city,a.country,a.icao].filter(Boolean).join(" • "))}</span></button>`).join(""):`<div class="airport-result">No matching airport</div>`;results.hidden=false};const delayed=debounce(render,80);input.addEventListener("input",()=>{selected=null;choice.textContent="No airport selected";onSelect(null);delayed()});input.addEventListener("focus",render);results.addEventListener("mousedown",e=>{const b=e.target.closest("[data-i]");if(b)choose(current[Number(b.dataset.i)])});input.addEventListener("keydown",e=>{const buttons=[...results.querySelectorAll("[data-i]")];if(e.key==="ArrowDown"){e.preventDefault();active=Math.min(active+1,buttons.length-1)}else if(e.key==="ArrowUp"){e.preventDefault();active=Math.max(active-1,0)}else if(e.key==="Enter"&&active>=0){e.preventDefault();choose(current[active]);return}else if(e.key==="Escape"){close();return}else return;buttons.forEach((b,i)=>b.classList.toggle("active",i===active));buttons[active]?.scrollIntoView({block:"nearest"})});document.addEventListener("pointerdown",e=>{if(!e.target.closest(".airport-picker"))close()});return{get:()=>selected,set:choose,clear:()=>{selected=null;input.value="";choice.textContent="No airport selected";onSelect(null)}}}
