import {CONFIG} from "./config.js";
import {loadAirports,createAirportPicker} from "./airports.js";
import {greatCircle,haversineNm,nearestIsoHour} from "./utils.js";
import {fetchTurbulence} from "./weather.js";
import {initMap,drawRoute} from "./map.js";
import {renderChart} from "./chart.js";
const $=id=>document.getElementById(id);let dep=null,arr=null,depPicker,arrPicker,busy=false;
function status(message,type=""){$("status").textContent=message;$("status").className=`status ${type}`.trim()}
function canRun(){$("analyseButton").disabled=busy||!dep||!arr||dep.id===arr.id}
function forecastOptions(){const select=$("forecastTime"),start=new Date(nearestIsoHour());select.innerHTML="";for(let h=0;h<=144;h+=3){const d=new Date(start.getTime()+h*3600000),option=document.createElement("option");option.value=d.toISOString();option.textContent=`${d.toLocaleString(undefined,{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"UTC",hour12:false})} UTC${h===0?" (nearest)":""}`;select.appendChild(option)}}
async function analyse(){if(!dep||!arr||busy)return;busy=true;canRun();$("analyseButton").textContent="Analysing…";try{const route=greatCircle(dep,arr,CONFIG.ROUTE_SAMPLES),fl=Number($("flightLevel").value),samples=await fetchTurbulence(route,fl,$("forecastTime").value,m=>status(m));drawRoute(samples,dep,arr);renderChart(samples);const values=samples.map(x=>x.index),mean=values.reduce((a,b)=>a+b,0)/values.length;$("distanceStat").textContent=`${Math.round(haversineNm(dep,arr)).toLocaleString()} NM`;$("meanStat").textContent=`${mean.toFixed(0)}/100`;$("maxStat").textContent=`${Math.max(...values).toFixed(0)}/100`;$("samplesStat").textContent=`${samples.length}/${CONFIG.ROUTE_SAMPLES}`;status(`Forecast rendered for ${samples[0].validTime} UTC at FL${fl}. Experimental estimate only.`,"success")}catch(e){console.error(e);status(`${e.name==="AbortError"?"Request timed out":e.message}. Check the browser console and try another forecast time.`,"error")}finally{busy=false;$("analyseButton").textContent="Analyse route";canRun()}}
async function init(){forecastOptions();initMap();const index=await loadAirports(m=>$("airportStatus").textContent=m);depPicker=createAirportPicker({input:$("departureInput"),results:$("departureResults"),choice:$("departureChoice"),index,onSelect:a=>{dep=a;canRun()}});arrPicker=createAirportPicker({input:$("arrivalInput"),results:$("arrivalResults"),choice:$("arrivalChoice"),index,onSelect:a=>{arr=a;canRun()}});const cdg=index.find(a=>a.iata==="CDG"),jfk=index.find(a=>a.iata==="JFK");if(cdg)depPicker.set(cdg);if(jfk)arrPicker.set(jfk);$("analyseButton").addEventListener("click",analyse);$("swapButton").addEventListener("click",()=>{if(!dep&&!arr)return;const a=dep,b=arr;a?arrPicker.set(a):arrPicker.clear();b?depPicker.set(b):depPicker.clear();canRun()});window.addEventListener("resize",()=>setTimeout(()=>window.dispatchEvent(new Event("leaflet-resize")),100));status("Choose airports and forecast time, then analyse the route.")}
window.addEventListener("DOMContentLoaded",init);
