import {CONFIG} from "./config.js";
import {clamp} from "./utils.js";
const LEVELS=[1000,925,850,700,600,500,400,350,300,250,200,150,100];
const FL_PRESSURE={200:466,240:393,280:329,300:301,320:275,340:251,350:238,360:225,380:200,400:188,420:176};
function pressureForFl(fl){return FL_PRESSURE[fl]||250}
function bracket(fl){const target=pressureForFl(fl),sorted=[...LEVELS].sort((a,b)=>b-a);let lower=sorted[0],upper=sorted.at(-1);for(let i=0;i<sorted.length-1;i++)if(sorted[i]>=target&&sorted[i+1]<=target){lower=sorted[i];upper=sorted[i+1];break}return{target,lower,upper}}
function windVector(speedKmh,dirDeg){const s=Number(speedKmh)/3.6,d=Number(dirDeg)*Math.PI/180;return{u:-s*Math.sin(d),v:-s*Math.cos(d)}}
function nearestTimeIndex(times,iso){const target=new Date(iso).getTime();let best=0,diff=Infinity;times.forEach((t,i)=>{const d=Math.abs(new Date(t+"Z").getTime()-target);if(d<diff){diff=d;best=i}});return best}
async function fetchJson(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),CONFIG.REQUEST_TIMEOUT_MS);try{const r=await fetch(url,{signal:controller.signal,cache:"no-store"});if(!r.ok){let detail="";try{detail=(await r.json()).reason||""}catch{}throw new Error(`Weather HTTP ${r.status}${detail?`: ${detail}`:""}`)}return await r.json()}finally{clearTimeout(timer)}}
export async function fetchTurbulence(route,fl,forecastIso,onProgress=()=>{}){const {lower,upper,target}=bracket(fl),vars=[`wind_speed_${lower}hPa`,`wind_direction_${lower}hPa`,`geopotential_height_${lower}hPa`,`wind_speed_${upper}hPa`,`wind_direction_${upper}hPa`,`geopotential_height_${upper}hPa`];onProgress(`Fetching GFS winds at ${lower}/${upper} hPa…`);const chunkSize=12,chunks=[];for(let i=0;i<route.length;i+=chunkSize)chunks.push(route.slice(i,i+chunkSize));const output=[];for(let ci=0;ci<chunks.length;ci++){onProgress(`Fetching GFS batch ${ci+1}/${chunks.length}…`);const chunk=chunks[ci],p=new URLSearchParams({latitude:chunk.map(x=>x.lat.toFixed(4)).join(","),longitude:chunk.map(x=>x.lon.toFixed(4)).join(","),hourly:vars.join(","),models:CONFIG.MODEL,wind_speed_unit:"kmh",timezone:"GMT",forecast_days:"7"}),data=await fetchJson(`${CONFIG.WEATHER_URL}?${p}`),responses=Array.isArray(data)?data:[data];responses.forEach((res,j)=>{const point=chunk[j];if(!point||!res?.hourly?.time)return;const k=nearestTimeIndex(res.hourly.time,forecastIso),h=res.hourly;const v1=windVector(h[`wind_speed_${lower}hPa`]?.[k],h[`wind_direction_${lower}hPa`]?.[k]),v2=windVector(h[`wind_speed_${upper}hPa`]?.[k],h[`wind_direction_${upper}hPa`]?.[k]),z1=Number(h[`geopotential_height_${lower}hPa`]?.[k]),z2=Number(h[`geopotential_height_${upper}hPa`]?.[k]),dv=Math.hypot(v2.u-v1.u,v2.v-v1.v),dz=Math.abs(z2-z1);if(!Number.isFinite(dv)||!Number.isFinite(dz)||dz<20)return;const shear=dv/dz,index=clamp((shear-0.002)*5200,0,100);output.push({...point,index,verticalShear:shear,windLower:Math.hypot(v1.u,v1.v),windUpper:Math.hypot(v2.u,v2.v),validTime:res.hourly.time[k],pressureTarget:target})})}if(output.length<2)throw new Error("The weather service returned too few valid pressure-level samples.");return output.sort((a,b)=>a.distanceNm-b.distanceNm)}
export function severity(index){if(index<20)return{label:"Calm",color:"#37d67a"};if(index<45)return{label:"Light",color:"#f4d35e"};if(index<70)return{label:"Moderate",color:"#ff9f43"};return{label:"Severe",color:"#ff4d64"}}
